#!/bin/bash

echo "=== Discord Raid Finder - Setup Instructions ==="
echo ""
echo "Step 1: Install Dependencies"
echo "  cd discord-raid-finder"
echo "  npm install"
echo ""
echo "Step 2: Configure Environment"
echo "  cp .env.example .env"
echo "  # Edit .env with your Discord credentials and AWS settings"
echo ""
echo "Step 3: Deploy Infrastructure (Terraform)"
echo "  cd .cicd/terraform"
echo "  terraform init"
echo "  terraform plan"
echo "  terraform apply"
echo "  cd ../.."
echo ""
echo "Step 4: Build TypeScript"
echo "  npm run build"
echo ""
echo "Step 5: Deploy Serverless Functions"
echo "  serverless deploy"
echo ""
echo "=== Discord Bot Setup ==="
echo ""
echo "1. Create a Discord Application at https://discord.com/developers/applications"
echo "2. Create a Bot and copy the token to DISCORD_BOT_TOKEN"
echo "3. Copy the Application ID to DISCORD_APPLICATION_ID"
echo "4. Enable these Privileged Gateway Intents:"
echo "   - SERVER MEMBERS INTENT"
echo "   - MESSAGE CONTENT INTENT"
echo "5. Add bot to your server with these scopes:"
echo "   - bot"
echo "   - applications.commands"
echo "6. Bot permissions needed:"
echo "   - Send Messages"
echo "   - Embed Links"
echo "   - Use Slash Commands"
echo "   - Read Message History"
echo "7. Get your Admin Role ID and add it to DISCORD_ADMIN_ROLE_ID"
echo ""
echo "=== Example Usage ==="
echo ""
echo "Create a raid event:"
echo "  /create-raid"
echo "    name: Mythic+ Night"
echo "    description: Weekly M+ runs!"
echo "    start-time: 2024-12-20 19:00"
echo "    roles: [{\"name\":\"Tank\",\"maxCount\":1,\"emoji\":\"🛡️\"},{\"name\":\"Healer\",\"maxCount\":1,\"emoji\":\"❤️\"},{\"name\":\"DPS\",\"maxCount\":3,\"emoji\":\"⚔️\"}]"
echo "    notice-minutes: 180,120,60,10"
echo "    weekly: true"
echo ""
echo "Cancel an event:"
echo "  /cancel-raid event-id: <event-id>"
echo ""
echo "List upcoming events:"
echo "  /list-raids"
